# Generated by Django 3.0.5 on 2020-07-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('pic', models.ImageField(blank=True, upload_to='admin_pics/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='coursetype_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='course_pics/')),
                ('fee', models.FloatField()),
                ('type', models.ManyToManyField(to='myadmin.CourseType')),
            ],
        ),
    ]
