# Generated by Django 3.0.5 on 2020-07-14 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('pic', models.ImageField(blank=True, upload_to='admin_pics/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='course_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBatch',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('batch_type', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('fee', models.FloatField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Course')),
                ('faculty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ManyToManyField(to='myadmin.CourseType'),
        ),
    ]
